// <auto-generated />
using System;
using ConsoleSolarSystem;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ConsoleSolarSystem.Migrations
{
    [DbContext(typeof(SolarSystemDbContext))]
    [Migration("20210118143712_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("SolarSystem.Moon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PlanetId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlanetId");

                    b.ToTable("Moons");
                });

            modelBuilder.Entity("SolarSystem.Planet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Diameter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberOfMoons")
                        .HasColumnType("int");

                    b.Property<string>("OrbitDistance")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrbitPeriod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PlanetType")
                        .HasColumnType("int");

                    b.Property<int>("StarId")
                        .HasColumnType("int");

                    b.Property<string>("SurfaceTemperatureMax")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SurfaceTemperatureMin")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("StarId");

                    b.ToTable("Planets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Diameter = "4,879",
                            Name = "Mercury",
                            NumberOfMoons = 0,
                            OrbitDistance = "57,900,000",
                            OrbitPeriod = "88",
                            PlanetType = 0,
                            StarId = 1,
                            SurfaceTemperatureMax = "-173",
                            SurfaceTemperatureMin = "-472"
                        });
                });

            modelBuilder.Entity("SolarSystem.Star", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Age")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CoreTemperature")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Diameter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SurfaceTemperature")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Stars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = "4,600,000,000",
                            CoreTemperature = "15,000,000",
                            Diameter = "1,392,684",
                            Name = "The Sun",
                            SurfaceTemperature = "5,500"
                        });
                });

            modelBuilder.Entity("SolarSystem.Moon", b =>
                {
                    b.HasOne("SolarSystem.Planet", null)
                        .WithMany("Moons")
                        .HasForeignKey("PlanetId");
                });

            modelBuilder.Entity("SolarSystem.Planet", b =>
                {
                    b.HasOne("SolarSystem.Star", "Star")
                        .WithMany("Planets")
                        .HasForeignKey("StarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Star");
                });

            modelBuilder.Entity("SolarSystem.Planet", b =>
                {
                    b.Navigation("Moons");
                });

            modelBuilder.Entity("SolarSystem.Star", b =>
                {
                    b.Navigation("Planets");
                });
#pragma warning restore 612, 618
        }
    }
}
